import { CalendarDays, Download, FileBarChart, FileCheck2, FileText, Send } from "lucide-react";

import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { pageSummaries } from "@/lib/data";

export default function ReportGenerationPage() {
  const summary = pageSummaries.reportGeneration;

  return (
    <AppShell>
      <PageHeader {...summary} />
      <section className="grid gap-6 xl:grid-cols-[0.85fr_1.15fr]">
        <Card className="glass-panel">
          <CardHeader>
            <CardTitle>Generate Report</CardTitle>
            <CardDescription>Select report type, period, and export destination.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {[
              { label: "Report type", value: "Executive Procurement Summary", icon: FileText },
              { label: "Period", value: "Q4 2026", icon: CalendarDays },
              { label: "Format", value: "PDF + Excel", icon: Download },
              { label: "Distribution", value: "Fleet Ops, Finance, Compliance", icon: Send }
            ].map((field) => {
              const Icon = field.icon;
              return (
                <div key={field.label} className="flex items-center justify-between rounded-lg border bg-white p-4">
                  <div className="flex items-center gap-3">
                    <Icon className="h-5 w-5 text-cyan-700" />
                    <span className="text-sm font-semibold">{field.label}</span>
                  </div>
                  <span className="max-w-48 truncate text-right text-sm text-muted-foreground">{field.value}</span>
                </div>
              );
            })}
            <Button className="w-full">
              <FileCheck2 className="h-4 w-4" />
              Generate Report
            </Button>
          </CardContent>
        </Card>

        <Card className="glass-panel">
          <CardHeader className="flex-row items-center justify-between">
            <div>
              <CardTitle>Report Library</CardTitle>
              <CardDescription>Audit-ready reports generated by the platform.</CardDescription>
            </div>
            <Badge variant="info">12 reports</Badge>
          </CardHeader>
          <CardContent>
            <div className="overflow-hidden rounded-lg border bg-white">
              <div className="grid grid-cols-4 bg-muted px-4 py-3 text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">
                <span>Report</span>
                <span>Scope</span>
                <span>Status</span>
                <span>Action</span>
              </div>
              {[
                ["Savings Performance", "Fleet-wide", "Ready"],
                ["Supplier Scorecard", "Top 30 suppliers", "Ready"],
                ["Optimization Audit", "PO-7814 batch", "Draft"],
                ["Lead Time Reduction", "Northern Europe", "Ready"]
              ].map(([name, scope, status]) => (
                <div key={name} className="grid grid-cols-4 items-center border-t px-4 py-3 text-sm">
                  <span className="font-semibold">{name}</span>
                  <span className="truncate text-muted-foreground">{scope}</span>
                  <Badge variant={status === "Ready" ? "success" : "warning"}>{status}</Badge>
                  <Button variant="outline" size="sm">
                    <FileBarChart className="h-4 w-4" />
                    Export
                  </Button>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </section>
    </AppShell>
  );
}
